number1 = int(input("Erste Zahl: "))
number2 = int(input("Zweite Zahl: "))
bin1 = "{:b}".format(number1)
bin2 = "{:b}".format(number2)
bin3 = "{:b}".format(number1 + number2)
width = len(bin3)
print("{:>{width}}".format(bin1,width = width + 1))
print("+{:>{width}}".format(bin2,width=width))
print("-"*(width + 1))
print("={:>{width}}".format(bin3,width=width))
